SELECT * FROM STUDENT;

INSERT INTO STUDENT
VALUES('1234', '홍길동', 95, 85, 89);

COMMIT;

SELECT S.*, 
       (JAVA+ORACLE+HTML) / 3  SCORE_AVG,
       ROUND((JAVA+ORACLE+HTML) / 3, 2)  SCORE_AVG
FROM STUDENT S;

SELECT STU_NAME AS ZZZ
FROM STUDENT;

SELECT AVG(PRICE)
FROM FRUIT;